apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment-1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-deployment-1
  template:
    metadata:
      labels:
        app: simple-deployment-1
    spec:
      containers:
      - name: app
        image: {{ .Values.image }}
        ports:
        - containerPort: 80